export const personalizationConst = {    
    GET_PERSONALIZATION_PENDING: "GET_PERSONALIZATION_PENDING",
    GET_PERSONALIZATION_SUCCESS: "GET_PERSONALIZATION_SUCCESS",
    GET_PERSONALIZATION_FAILURE: "GET_PERSONALIZATION_FAILURE",
    
    SAVE_PERSONALIZATION_PENDING: "SAVE_PERSONALIZATION_PENDING",
    SAVE_PERSONALIZATION_SUCCESS: "SAVE_PERSONALIZATION_SUCCESS",
    SAVE_PERSONALIZATION_FAILURE: "SAVE_PERSONALIZATION_FAILURE",

}